DROP TABLE IF EXISTS products CASCADE;
CREATE TABLE products (
    id SERIAL primary key,
    name VARCHAR(255) NOT NULL CHECK (name != ''),
    description TEXT,
    price NUMERIC(10,2) NOT NULL,
    picture_url VARCHAR
);


INSERT INTO products (name, description, price, picture_url) VALUES ('toilet','a fixed receptacle into which a person may urinate or defecate, typically consisting of a large bowl connected to a system for flushing away the waste into a sewer or septic tank.', 74.12 , 'https://www.randomlists.com/img/things/toilet.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('spoon','a utensil for use in eating, stirring, measuring, ladling, etc., consisting of a small, shallow bowl with a handle.', 9.99, 'https://www.randomlists.com/img/things/spoon.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('leg warmers','a footless, stockinglike knitted covering for the leg, usually worn over tights, trousers, boots, etc., for warmth, as in a dance class or while exercising, or as a fashion accessory.', 19.99 , 'https://www.randomlists.com/img/things/leg_warmers.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('bag','a container or receptacle of leather, plastic, cloth, paper, etc., capable of being closed at the mouth; pouch.', 39.80, 'https://www.randomlists.com/img/things/bag.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('nail file','a small file of metal or cardboard, for trimming, smoothing, or shaping the fingernails and sometimes having a point for removing dirt from under them.', 6.99, 'https://www.randomlists.com/img/things/nail_file.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('ice cube tray','Ice cube trays are designed to be filled with water, then placed in a freezer until the water freezes into ice, producing ice cubes. Ice trays are often flexible, so the frozen cubes can be easily removed by flexing the tray.', 29.10, 'https://www.randomlists.com/img/things/ice_cube_tray.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('clay pot','A type of pot that is commonly used to cook a variety of sauces, stews, egg, potato, vegetable, meat, poultry, and fish dishes. Clay pots allow foods to be cooked with moist heat, both from the juices of the foods as they cook as well as moisture added to the porous clay.',5.99 , 'https://www.randomlists.com/img/things/clay_pot.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('couch','a piece of furniture for seating from two to four people, typically in the form of a bench with a back, sometimes having an armrest at one or each end, and partly or wholly upholstered and often fitted with springs, tailored cushions, skirts, etc.; sofa.', 280.99 , 'https://www.randomlists.com/img/things/couch.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('cell phone','A cellular phone is a telecommunication device that uses radio waves over a networked area (cells) and is served through a cell site or base station at a fixed location, enabling calls to transmit wirelessly over a wide range, to a fixed landline or via the Internet.', 380.11, 'https://www.randomlists.com/img/things/cell_phone.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('lamp shade','a cover that softens or directs the light of a lamp.', 9.99, 'https://www.randomlists.com/img/things/lamp_shade.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('apple','the usually round, red or yellow, edible fruit of a small tree, Malus sylvestris, of the rose family.', 0.99, 'https://www.randomlists.com/img/things/apple.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('rug','a thick fabric for covering part of a floor, often woven of wool and often having an oblong shape with a border design.',39.99 , 'https://www.randomlists.com/img/things/rug.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('model car','A model car, or toy car, is a miniature representation of an automobile. Other miniature motor vehicles, such as trucks, buses, or even ATVs, etc. are often included in this general category.', 14.99 , 'https://www.randomlists.com/img/things/model_car.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('bow','a decorative interlacing of ribbon or other fabrics, usually having two loops and two loose ends', 7.99 , 'https://www.randomlists.com/img/things/bow.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('box','a container, case, or receptacle, usually rectangular, of wood, metal, cardboard, etc., and often with a lid or removable cover.', 3.99 , 'https://www.randomlists.com/img/things/box.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('packing peanuts','Foam peanuts, also known as foam popcorn, snissues, packing peanuts, or packing noodles, are a common loose-fill packaging and cushioning material used to prevent damage to fragile objects during shipping.', 9.99 , 'https://www.randomlists.com/img/things/packing_peanuts.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('rubber duck','A rubber duck or a rubber ducky is a toy shaped like a stylized duck, generally yellow with a flat base. It may be made of rubber or rubber-like material such as vinyl plastic.', 19.99 , 'https://www.randomlists.com/img/things/rubber_duck.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('cinder block','a lightweight building brick made from small cinders mixed with sand and cement; a breeze block.', 14.99 , 'https://www.randomlists.com/img/things/cinder_block.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('stop sign','a sign telling drivers to stop and wait until they can continue safely.', 39.99 , 'https://www.randomlists.com/img/things/stop_sign.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('blanket','a large piece of woollen or similar material used as a covering on a bed or elsewhere for warmth.', 7.99 , 'https://www.randomlists.com/img/things/blanket.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('street lights','a light illuminating a road, typically mounted on a tall post.', 799.99 , 'https://www.randomlists.com/img/things/street_lights.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('mouse pad','A mouse pad is a thin rubber or plastic cushion of about about 12 square inches or less with a plastic or textured surface. A mouse pad provides better traction and more precise cursor movement for a mouse than a desktop or other surface. Sometimes, a mouse pad includes a cushion for the users hand or wrist.', 9.99 , 'https://www.randomlists.com/img/things/mouse_pad.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('toe ring','a ring worn on the toe.', 79.87 , 'https://www.randomlists.com/img/things/toe_ring.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('clamp','a brace, band, or clasp for strengthening or holding things together.', 2.99 , 'https://www.randomlists.com/img/things/clamp.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('rusty nail','nail covered with or affected by rust.', 0.79 , 'https://www.randomlists.com/img/things/rusty_nail.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('headphones','Headphones are a pair of small speakers used for listening to sound from a computer, music player or other such electronic device. Headphones originally consisted of one speaker for each ear, connected by a band over the head.', 89.11 , 'https://www.randomlists.com/img/things/headphones.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('book','A book is a medium for recording information in the form of writing or images, typically composed of many pages (made of papyrus, parchment, vellum, or paper) bound together and protected by a cover.', 19.99 , 'https://www.randomlists.com/img/things/book.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('monitor','A monitor is an electronic visual computer display that includes a screen, circuitry and the case in which that circuitry is enclosed.', 109.99 , 'https://www.randomlists.com/img/things/monitor.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('tissue box','Tissue boxes are made out of cardboard, so they can be recycled alongside larger cardboard packages.', 3.99 , 'https://www.randomlists.com/img/things/tissue_box.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('beef','beef, flesh of mature cattle, as distinguished from veal, the flesh of calves. The best beef is obtained from early maturing, special beef breeds. High-quality beef has firm, velvety, fine-grained lean, bright red in colour and well-marbled. The fat is smooth, creamy white, and well distributed.', 19.99 , 'https://www.randomlists.com/img/things/beef.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('floor','the lower surface of a room, on which one may walk.', 199.99 , 'https://www.randomlists.com/img/things/floor.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('towel','a piece of thick absorbent cloth or paper used for drying oneself or wiping things dry.', 7.99 , 'https://www.randomlists.com/img/things/towel.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('bed','a piece of furniture on which a person sleeps or rests.', 299.99 , 'https://www.randomlists.com/img/things/bed.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('fake flowers','Soft touch artificial flowers look and feel like real touch flowers but are instead made from a PU foam that is dyed, printed, and assembled to look like real flowers. ', 16.99 , 'https://www.randomlists.com/img/things/fake_flowers.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('vase','A vase is an open container. It can be made from a number of materials, such as ceramics, glass, non-rusting metals, such as aluminium, brass, bronze, or stainless steel.', 14.99 , 'https://www.randomlists.com/img/things/vase.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('glass','a hard, brittle substance, typically transparent or translucent, made by fusing sand with soda and lime and cooling rapidly. It is used to make windows, drinking containers, and other articles.', 7.99 , 'https://www.randomlists.com/img/things/glass.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('shoes','A shoe is an item of footwear intended to protect and comfort the human foot. Shoes are also used as an item of decoration and fashion. The design of shoes has varied enormously through time and from culture to culture, with form originally being tied to function.', 120.99 , 'https://www.randomlists.com/img/things/shoes.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('socks',' A garment that covers the foot and part of the leg usually made of cotton or wool and worn for warmth or for protection from abrasion from a shoe or boot.', 8.99 , 'https://www.randomlists.com/img/things/socks.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('sponge','Sponge is a very light soft substance with lots of little holes in it, which can be either artificial or natural. It is used to clean things or as a soft layer.', 3.90 , 'https://www.randomlists.com/img/things/sponge.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('lip gloss','A transparent, sometimes colored cosmetic ointment applied to the lips as a moisturizer and to give a shiny appearance.', 5.99 , 'https://www.randomlists.com/img/things/lip_gloss.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('bracelet','A bracelet is an article of jewellery that is worn around the wrist. Bracelets may serve different uses, such as being worn as an ornament. When worn as ornaments, bracelets may have a supportive function to hold other items of decoration, such as charms.', 18.99 , 'https://www.randomlists.com/img/things/bracelet.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('balloon','a small coloured rubber bag which is inflated with air and then sealed at the neck, used as a childs toy or a decoration.', 1.99 , 'https://www.randomlists.com/img/things/balloon.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('cookie jar','a container with a lid for storing biscuits: Make these walnut cookies up to 4 days ahead; store in a cookie jar or tightly sealed container.', 7.99 , 'https://www.randomlists.com/img/things/cookie_jar.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('rubber band','A rubber band (also known as an elastic band, gum band or lacky band) is a loop of rubber, usually ring or oval shaped, and commonly used to hold multiple objects together. ', 3.99 , 'https://www.randomlists.com/img/things/rubber_band.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('picture frame','A picture frame is a protective and decorative edging for a picture, such as a painting or photograph. It makes displaying the work safer and easier and both sets the picture apart from its surroundings and aesthetically integrates it with them.', 19.99 , 'https://www.randomlists.com/img/things/picture_frame.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('mp3 player','An MP3 player, often called a digital music player or portable audio player, is a handheld device that plays and stores audio and video files. The device is called an MP3 player because the digital format used most commonly on the device is called an MP3.', 99.99 , 'https://www.randomlists.com/img/things/mp3_player.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('face wash','Face wash is a gentle liquid soap that gives deep pore cleansing. It is an easiest way to get rid of the extra oil, makeup and dust particles from the skin. It cleans face gently thereby leaving a fresh and glowing skin. It is a hygienic way and convenient way to take care of skin.', 4.99 , 'https://www.randomlists.com/img/things/face_wash.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('thermometer','A thermometer is an instrument that measures temperature. It can measure the temperature of a solid such as food, a liquid such as water, or a gas such as air.', 8.66 , 'https://www.randomlists.com/img/things/thermometer.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('wallet','A wallet is a flat case or pouch that can be used to carry such small personal items as paper currency, credit cards, and identification documents (drivers license, identification card, club card, etc.), photographs, transit pass, business cards and other paper or laminated cards.', 12.99 , 'https://www.randomlists.com/img/things/wallet.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('magnet','A magnet is a material or object that produces a magnetic field. This magnetic field is invisible but is responsible for the most notable property of a magnet: a force that pulls on other ferromagnetic materials, such as iron, steel, nickel, cobalt, etc. and attracts or repels other magnets.', 4.99 , 'https://www.randomlists.com/img/things/magnet.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('soy sauce packet','Soy sauce (also called simply soy in American English[1] and sometimes soya sauce in British English)[2] is a liquid condiment of Chinese origin, traditionally made from a fermented paste of soybeans, roasted grain, brine, and Aspergillus oryzae or Aspergillus sojae molds.[3] It is considered to contain a strong umami flavor.', 14.99 , 'https://www.randomlists.com/img/things/soy_sauce_packet.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('piano', 'A piano is a large musical instrument that you play by pressing black and white keys on a keyboard. Most people play a piano with their fingers, but Jerry Lee Lewis played with his fingers, feet, elbows, and, ahem, backside. A piano makes a sound when each key moves a small hammer that strikes a metal string.',2890.11 , 'https://www.randomlists.com/img/things/piano.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('chocolate', 'chocolate, food product made from cocoa beans, consumed as candy and used to make beverages and to flavour or coat various confections and bakery products. Rich in carbohydrates, it is an excellent source of quick energy, and it also contains minute amounts of the stimulating alkaloids theobromine and caffeine.',4.99 , 'https://www.randomlists.com/img/things/chocolate.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('toothbrush', 'A toothbrush is an oral hygiene tool used to clean the teeth, gums, and tongue. It consists of a head of tightly clustered bristles, atop of which toothpaste can be applied, mounted on a handle which facilitates the cleaning of hard-to-reach areas of the mouth.', 3.99, 'https://www.randomlists.com/img/things/toothbrush.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('boom box', 'A boombox is a transistorized portable music player featuring one or two cassette tape recorder/players and AM/FM radio, generally with a carrying handle. Beginning in the mid 1980s, a CD player was often included. Sound is delivered through an amplifier and two or more integrated loudspeakers.', 56.99, 'https://www.randomlists.com/img/things/boom_box.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('camera', 'a device for recording visual images in the form of photographs, film, or video signals.',491.91 , 'https://www.randomlists.com/img/things/camera.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('sketch pad', 'a pad of drawing paper for sketching on.', 4.99, 'https://www.randomlists.com/img/things/sketch_pad.webp');
INSERT INTO products (name, description, price, picture_url) VALUES ('candle', 'A candle is an ignitable wick embedded in wax, or another flammable solid substance such as tallow, that provides light, and in some cases, a fragrance. A candle can also provide heat or a method of keeping time.',4.99 , 'https://www.randomlists.com/img/things/candle.webp');
